name: Compilar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar con Buildozer
        run: yes | buildozer android debug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: radio-local-apk
          path: bin/*.apk
