name: Compilar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Compilar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: radio-local-apk
          path: ${{ steps.buildozer.outputs.filename }}
